apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-local
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-local-claim
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-local
