- hosts: master
  become: yes
  #gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: Wait until port 6443 on master is reachable
      wait_for:
        host: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}"
        port: 6443
        timeout: 10

    - name: Join worker to the Kubernetes cluster
      shell: "{{ hostvars[groups['master'][0]].join_command }} >> node_joined.log"
      args:
        chdir: $HOME
        creates: node_joined.log
      register: hello

    - debug: msg={{ hello.stdout }}
