apiVersion: apps/v1
kind: Deployment
metadata:
  name: matnn
    #  namespace: default
spec:
  selector:
    matchLabels:
      app: matnn
  template:
    metadata:
      labels:
        app: matnn
    spec:
      containers:
      - name: matnn
        image: intamixx/matnn:0.2
        ports:
        - name: nodejs
          containerPort: 9090
        - name: fastapi
          containerPort: 8000
        securityContext:
          privileged: true       
        volumeMounts:
        - name: config-volume
          mountPath: /fastapi/config
        - name: ssl-volume
          mountPath: /nodejs/ssl
        - name: nfs
          mountPath: /mnt
      volumes:
      - name: config-volume
        configMap:
          name: matnn-config
          items:
            - key: matnn-config
              path: matnn.ini
      - name: ssl-volume
        configMap:
          name: matnn-config
          items:
            - key: ssl-privatekey
              path: privatekey.pem
            - key: ssl-certificate
              path: certificate.pem
      - name: nfs
        nfs:
          server: 10.42.3.107
          path: /exports
      restartPolicy: Always
